package com.epam.gymcrmsystemapi.model.trainer.specialization;

public enum SpecializationType {

    PERSONAL_TRAINER,
    FITNESS_AND_WELLNESS_TRAINER,
    STRENGTH_TRAINING_COACH,
    FUNCTIONAL_TRAINING_COACH,
    CROSSFIT_COACH,
    PILATES_INSTRUCTOR,
    BODYBUILDING_COACH,
    MARTIAL_ARTS_COACH,
    CARDIO_TRAINING_COACH,
    STRETCHING_COACH,
    SWIMMING_COACH,
    GROUP_TRAINING_INSTRUCTOR,
    FITNESS_AEROBICS_COACH,
    REHABILITATION_TRAINING_COACH,
    SPORTS_DIET_COACH,
    CYCLING_COACH,
    GYMNASTICS_COACH,
    TRX_TRAINING_COACH,
    SPECIAL_NEEDS_TRAINING_COACH

}
