spring:
  config:
    activate:
      on-profile: local-dev
    import: optional:file:.env-local-dev[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gym
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: ${SPRING_SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, info, prometheus