spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local-dev
  jpa:
    open-in-view: false

password:
  strength: 10
  length: 10
  characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()