spring:
  config:
    activate:
      on-profile: local-dev
    import: optional:file:.env-local-dev[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${db-name}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: ${SPRING_SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always

host: http://localhost:8080
db-name: gym

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

custom:
  health:
    db-response-time:
      enabled: true
    api:
      enabled: true