spring:
  application:
    name: gym-crm-system-api
  profiles:
    active: local-dev
  jpa:
    open-in-view: false

password:
  strength: 10
  length: 10
  characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()

gym-crm-system:
  security:
    jwt:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8ie
      access-expire-in: 10m
      refresh-expire-in: 3d
    admins:
      defaultadmin:
        first-name: default
        last-name: admin
        password: qwertyuiop

trainer-workload-api:
  name: trainer-workload-api
  uri: /api/v1/training

resilience4j.circuitbreaker:
  instances:
    add:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException

    delete:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 15s
      failureRateThreshold: 60
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException