spring:
  config:
    activate:
      on-profile: test
    import: optional:file:.env-test[.properties]
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SPRING_SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: DEBUG
    com.epam.gymcrmsystemapi: DEBUG

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"

host: http://localhost:8080
db-name: gym-test

custom:
  health:
    db-response-time:
      enabled: true
    api:
      enabled: true