spring:
  config:
    activate:
      on-profile: local-dev
    import: optional:file:.env-local-dev[.properties]
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainings_db
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SPRING_SERVER_PORT_WORKLOAD}
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true