spring:
  config:
    activate:
      on-profile: local-dev
    import: optional:file:.env-local-dev[.properties]
  datasource:
    url: jdbc:h2:mem:trainings_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SPRING_SERVER_PORT_WORKLOAD}
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized