package com.epam.gymcrmsystemapi.model.training.type;

public enum Type {

    STRENGTH_TRAINING,
    CARDIO_WORKOUT,
    FUNCTIONAL_TRAINING,
    CROSSFIT_WORKOUT,
    PILATES_SESSION,
    BODYBUILDING_PROGRAM,
    MARTIAL_ARTS_TRAINING,
    SWIMMING_SESSION,
    GROUP_FITNESS_CLASS,
    FITNESS_AEROBICS,
    REHABILITATION_WORKOUT,
    NUTRITION_AND_DIET_PLAN,
    CYCLING_WORKOUT,
    GYMNASTICS_TRAINING,
    TRX_TRAINING,
    SPECIAL_NEEDS_TRAINING,
    STRETCHING_SESSION,
    BOOTCAMP_WORKOUT

}
